services:
  mysql:
    image: mysql:8.0
    container_name: sec-mysql
    ports:
      - "3308:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=dbsec
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - java-sec-volume:/var/lib/mysql

volumes:
  java-sec-volume:
